### ISSUE TITLE
برنامه دیگه کار نمیکنه

### ISSUE THREAD

**Issue by sheikhartin** [erfansaberi/CarPriceGuess#1]
سایت باما برای افزایش تماس با فروشنده از این به بعد قیمت خودرو ها رو نشون نمیده (همه به صورت توافقی نمایش داده میشه) و در نهایت برنامه نمیتونه قیمت رو اسکرپ کنه

**Comment by dieseyed** [comment]
یبس

**Comment by erfansaberi** [comment]
آره خب، منطقا دیگه قیمتی وجود نداره که اسکرپ بشه، ولی برنامه اینجا باشه ضرری نداره
باید یه برنامه بنویسیم که زنگ بزنه به فروشنده ها و قیمت ها رو اسکرپ کنه :)))
